TCF-5 Map
Corgam/SS23_ADSP_TCF pull request #66
Opened 2023-05-24 17:56 UTC by flori950

2023-05-25 13:54 UTC, thdrbrkw requested changes
Can you please remove Shrek

2023-05-25 13:56 UTC, thdrbrkw commented on frontend/src/app/shared/map/map.component.ts
> +
Here an `EventEmitter` is missing which emits the value of the clicked coordinates

2023-05-25 13:57 UTC, thdrbrkw commented on frontend/src/app/shared/map/map.component.html
> +<div id="map" style="width: 100%; height: 400px;"></div>
`height: 100%`

2023-05-29 12:44 UTC, thdrbrkw commented
Committed changes:
- made map 100% for width and height
- using point instead of logo/png
- only one point displayed
- changed displayed coordinate value to long/lat

2023-05-29 12:47 UTC, thdrbrkw approved these changes

2023-05-29 13:02 UTC, guttenberger approved these changes

2023-05-29 13:03 UTC, merged